### ISSUE TITLE
Reset password screen looks ugly

### ISSUE THREAD

**Issue by jessedusty** [packetriot/packetriot.com#2]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1495092/89687626-8ede0900-d8ce-11ea-9ec7-eae36740269d.png">

The first and third fields are missing `class="input'` as far as I can tell.

**Comment by jessedusty** [comment]
(from url path: https://packetriot.com/reset/******)

**Comment by jborak** [comment]
Thanks for reporting, fixed in the latest update of the website.
